/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DatabasesRouteImport } from './routes/databases'
import { Route as ConnectCliRouteImport } from './routes/connect-cli'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AgentGuideRouteImport } from './routes/agent-guide'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspacesWorkspaceIdRouteImport } from './routes/workspaces.$workspaceId'
import { Route as SignupClerkPathRouteImport } from './routes/signup.$clerkPath'
import { Route as LoginClerkPathRouteImport } from './routes/login.$clerkPath'
import { Route as AgentsAddRouteImport } from './routes/agents_.add'

const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabasesRoute = DatabasesRouteImport.update({
  id: '/databases',
  path: '/databases',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectCliRoute = ConnectCliRouteImport.update({
  id: '/connect-cli',
  path: '/connect-cli',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentGuideRoute = AgentGuideRouteImport.update({
  id: '/agent-guide',
  path: '/agent-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesWorkspaceIdRoute = WorkspacesWorkspaceIdRouteImport.update({
  id: '/$workspaceId',
  path: '/$workspaceId',
  getParentRoute: () => WorkspacesRoute,
} as any)
const SignupClerkPathRoute = SignupClerkPathRouteImport.update({
  id: '/$clerkPath',
  path: '/$clerkPath',
  getParentRoute: () => SignupRoute,
} as any)
const LoginClerkPathRoute = LoginClerkPathRouteImport.update({
  id: '/$clerkPath',
  path: '/$clerkPath',
  getParentRoute: () => LoginRoute,
} as any)
const AgentsAddRoute = AgentsAddRouteImport.update({
  id: '/agents_/add',
  path: '/agents/add',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/agent-guide': typeof AgentGuideRoute
  '/agents': typeof AgentsRoute
  '/connect-cli': typeof ConnectCliRoute
  '/databases': typeof DatabasesRoute
  '/docs': typeof DocsRoute
  '/downloads': typeof DownloadsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRouteWithChildren
  '/mcp': typeof McpRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRouteWithChildren
  '/templates': typeof TemplatesRoute
  '/workspaces': typeof WorkspacesRouteWithChildren
  '/agents/add': typeof AgentsAddRoute
  '/login/$clerkPath': typeof LoginClerkPathRoute
  '/signup/$clerkPath': typeof SignupClerkPathRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/agent-guide': typeof AgentGuideRoute
  '/agents': typeof AgentsRoute
  '/connect-cli': typeof ConnectCliRoute
  '/databases': typeof DatabasesRoute
  '/docs': typeof DocsRoute
  '/downloads': typeof DownloadsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRouteWithChildren
  '/mcp': typeof McpRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRouteWithChildren
  '/templates': typeof TemplatesRoute
  '/workspaces': typeof WorkspacesRouteWithChildren
  '/agents/add': typeof AgentsAddRoute
  '/login/$clerkPath': typeof LoginClerkPathRoute
  '/signup/$clerkPath': typeof SignupClerkPathRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/agent-guide': typeof AgentGuideRoute
  '/agents': typeof AgentsRoute
  '/connect-cli': typeof ConnectCliRoute
  '/databases': typeof DatabasesRoute
  '/docs': typeof DocsRoute
  '/downloads': typeof DownloadsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRouteWithChildren
  '/mcp': typeof McpRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRouteWithChildren
  '/templates': typeof TemplatesRoute
  '/workspaces': typeof WorkspacesRouteWithChildren
  '/agents_/add': typeof AgentsAddRoute
  '/login/$clerkPath': typeof LoginClerkPathRoute
  '/signup/$clerkPath': typeof SignupClerkPathRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/agent-guide'
    | '/agents'
    | '/connect-cli'
    | '/databases'
    | '/docs'
    | '/downloads'
    | '/forgot-password'
    | '/login'
    | '/mcp'
    | '/settings'
    | '/signup'
    | '/templates'
    | '/workspaces'
    | '/agents/add'
    | '/login/$clerkPath'
    | '/signup/$clerkPath'
    | '/workspaces/$workspaceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/agent-guide'
    | '/agents'
    | '/connect-cli'
    | '/databases'
    | '/docs'
    | '/downloads'
    | '/forgot-password'
    | '/login'
    | '/mcp'
    | '/settings'
    | '/signup'
    | '/templates'
    | '/workspaces'
    | '/agents/add'
    | '/login/$clerkPath'
    | '/signup/$clerkPath'
    | '/workspaces/$workspaceId'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/agent-guide'
    | '/agents'
    | '/connect-cli'
    | '/databases'
    | '/docs'
    | '/downloads'
    | '/forgot-password'
    | '/login'
    | '/mcp'
    | '/settings'
    | '/signup'
    | '/templates'
    | '/workspaces'
    | '/agents_/add'
    | '/login/$clerkPath'
    | '/signup/$clerkPath'
    | '/workspaces/$workspaceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AgentGuideRoute: typeof AgentGuideRoute
  AgentsRoute: typeof AgentsRoute
  ConnectCliRoute: typeof ConnectCliRoute
  DatabasesRoute: typeof DatabasesRoute
  DocsRoute: typeof DocsRoute
  DownloadsRoute: typeof DownloadsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRouteWithChildren
  McpRoute: typeof McpRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRouteWithChildren
  TemplatesRoute: typeof TemplatesRoute
  WorkspacesRoute: typeof WorkspacesRouteWithChildren
  AgentsAddRoute: typeof AgentsAddRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/databases': {
      id: '/databases'
      path: '/databases'
      fullPath: '/databases'
      preLoaderRoute: typeof DatabasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect-cli': {
      id: '/connect-cli'
      path: '/connect-cli'
      fullPath: '/connect-cli'
      preLoaderRoute: typeof ConnectCliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-guide': {
      id: '/agent-guide'
      path: '/agent-guide'
      fullPath: '/agent-guide'
      preLoaderRoute: typeof AgentGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$workspaceId': {
      id: '/workspaces/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof WorkspacesWorkspaceIdRouteImport
      parentRoute: typeof WorkspacesRoute
    }
    '/signup/$clerkPath': {
      id: '/signup/$clerkPath'
      path: '/$clerkPath'
      fullPath: '/signup/$clerkPath'
      preLoaderRoute: typeof SignupClerkPathRouteImport
      parentRoute: typeof SignupRoute
    }
    '/login/$clerkPath': {
      id: '/login/$clerkPath'
      path: '/$clerkPath'
      fullPath: '/login/$clerkPath'
      preLoaderRoute: typeof LoginClerkPathRouteImport
      parentRoute: typeof LoginRoute
    }
    '/agents_/add': {
      id: '/agents_/add'
      path: '/agents/add'
      fullPath: '/agents/add'
      preLoaderRoute: typeof AgentsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LoginRouteChildren {
  LoginClerkPathRoute: typeof LoginClerkPathRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginClerkPathRoute: LoginClerkPathRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

interface SignupRouteChildren {
  SignupClerkPathRoute: typeof SignupClerkPathRoute
}

const SignupRouteChildren: SignupRouteChildren = {
  SignupClerkPathRoute: SignupClerkPathRoute,
}

const SignupRouteWithChildren =
  SignupRoute._addFileChildren(SignupRouteChildren)

interface WorkspacesRouteChildren {
  WorkspacesWorkspaceIdRoute: typeof WorkspacesWorkspaceIdRoute
}

const WorkspacesRouteChildren: WorkspacesRouteChildren = {
  WorkspacesWorkspaceIdRoute: WorkspacesWorkspaceIdRoute,
}

const WorkspacesRouteWithChildren = WorkspacesRoute._addFileChildren(
  WorkspacesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AgentGuideRoute: AgentGuideRoute,
  AgentsRoute: AgentsRoute,
  ConnectCliRoute: ConnectCliRoute,
  DatabasesRoute: DatabasesRoute,
  DocsRoute: DocsRoute,
  DownloadsRoute: DownloadsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRouteWithChildren,
  McpRoute: McpRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRouteWithChildren,
  TemplatesRoute: TemplatesRoute,
  WorkspacesRoute: WorkspacesRouteWithChildren,
  AgentsAddRoute: AgentsAddRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
