#!/usr/bin/env bash
# bench_compare.sh
#
# Full comparison run: AFS cold, AFS warm, local.
#
# Usage:
#   scripts/bench_compare.sh [rounds] [out-dir]
#
# Assumes ~/.claude is the AFS mount and /tmp/claude-local is an rsync'd
# local copy of the same tree. Stages the local copy on first run.
#
# Writes:
#   <out-dir>/afs-cold.csv
#   <out-dir>/afs-warm.csv
#   <out-dir>/local.csv
#   <out-dir>/summary.md

set -euo pipefail

ROUNDS="${1:-5}"
OUT_DIR="${2:-/tmp/afs-perf-run-$(date +%Y%m%d-%H%M%S)}"
mkdir -p "$OUT_DIR"

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BENCH="$REPO_ROOT/scripts/bench_claude_fs.sh"
AFS_BIN="$REPO_ROOT/afs"
AFS_MOUNT="$HOME/.claude"
LOCAL_MIRROR="/tmp/claude-local"

section() { printf '\n==== %s ====\n' "$*" >&2; }

# ---- 1. stage local mirror --------------------------------------------------
section "staging local mirror at $LOCAL_MIRROR"
# Exclude AppleDouble sidecars: they are generated by macOS on the fly and
# will be actively written to during any parallel Claude Code session,
# which races with rsync. They are also not persisted by AFS (see
# mount/internal/nfsfs/appledouble.go) and would be regenerated anyway.
rsync -a --delete --exclude='._*' "$AFS_MOUNT/" "$LOCAL_MIRROR/" 2>&1 | tail -5

# sanity
afs_files=$(find "$AFS_MOUNT" -type f 2>/dev/null | wc -l | tr -d ' ')
loc_files=$(find "$LOCAL_MIRROR" -type f 2>/dev/null | wc -l | tr -d ' ')
echo "  afs files=$afs_files  local files=$loc_files" >&2

# ---- 2. AFS cold: down + up + immediate bench -------------------------------
section "AFS cold (down + up + bench)"
"$AFS_BIN" down >/dev/null 2>&1 || true
sleep 1
"$AFS_BIN" up >/dev/null 2>&1
# wait for mount to be visible
for i in 1 2 3 4 5; do
  if ls "$AFS_MOUNT" >/dev/null 2>&1; then break; fi
  sleep 1
done
"$BENCH" "$AFS_MOUNT" "$ROUNDS" afs-cold > "$OUT_DIR/afs-cold.csv"

# ---- 3. AFS warm: same mount, run again -------------------------------------
section "AFS warm (caches hot from previous run)"
"$BENCH" "$AFS_MOUNT" "$ROUNDS" afs-warm > "$OUT_DIR/afs-warm.csv"

# ---- 4. Local -------------------------------------------------------------
section "Local mirror"
"$BENCH" "$LOCAL_MIRROR" "$ROUNDS" local > "$OUT_DIR/local.csv"

# ---- 5. summary markdown ---------------------------------------------------
section "writing summary"
python3 - "$OUT_DIR" <<'PY'
import csv, os, sys
out = sys.argv[1]
def load(name):
    rows = {}
    with open(os.path.join(out, name)) as f:
        for r in csv.DictReader(f):
            rows[r["op"]] = r
    return rows
cold = load("afs-cold.csv")
warm = load("afs-warm.csv")
local = load("local.csv")
ops = [o for o in local.keys() if o != "_harness_noop"]
harness_local = float(local.get("_harness_noop",{}).get("median_ms","0") or 0)
harness_warm  = float(warm.get("_harness_noop",{}).get("median_ms","0") or 0)
harness_cold  = float(cold.get("_harness_noop",{}).get("median_ms","0") or 0)

def f(x):
    try: return float(x)
    except: return 0.0

lines = []
lines.append("# Bench: AFS vs local ~/.claude\n")
lines.append(f"Harness noop (overhead): local={harness_local:.2f}ms afs-warm={harness_warm:.2f}ms afs-cold={harness_cold:.2f}ms\n")
lines.append("")
lines.append("| op | local (ms) | afs warm (ms) | afs cold (ms) | warm/local | cold/local |")
lines.append("|----|-----------:|--------------:|--------------:|-----------:|-----------:|")
for op in ops:
    if op not in cold or op not in warm: continue
    l = f(local[op]["median_ms"])
    w = f(warm[op]["median_ms"])
    c = f(cold[op]["median_ms"])
    ratio_w = (w / l) if l > 0 else 0
    ratio_c = (c / l) if l > 0 else 0
    lines.append(f"| {op} | {l:.2f} | {w:.2f} | {c:.2f} | {ratio_w:.1f}x | {ratio_c:.1f}x |")
open(os.path.join(out, "summary.md"), "w").write("\n".join(lines) + "\n")
print("wrote", os.path.join(out, "summary.md"))
PY

echo
echo "Done. Results in: $OUT_DIR"
cat "$OUT_DIR/summary.md"
